# GoReleaser v2 Configuration
# Triggered by pushing v* tags (e.g., v1.0.0)

version: 2

project_name: alert-bridge

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: alert-bridge
    main: ./cmd/alert-bridge
    binary: alert-bridge
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - config/config.example.yaml

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

dockers_v2:
  - id: alert-bridge-docker
    ids:
      - alert-bridge
    dockerfile: Dockerfile.goreleaser
    images:
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}"
    tags:
      - "{{ .Tag }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
    extra_files:
      - config/config.example.yaml

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat.*"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix.*"
      order: 1
    - title: Documentation
      regexp: "^.*docs.*"
      order: 2
    - title: Performance
      regexp: "^.*perf.*"
      order: 3
    - title: Refactor
      regexp: "^.*refactor.*"
      order: 4
    - title: Others
      order: 999
  filters:
    exclude:
      - "^chore"
      - "^ci"
      - "^test"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: qj0r9j0vc2
    name: alert-bridge
  name_template: "{{ .Tag }}"
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Alert Bridge {{ .Tag }}

    ### Installation

    #### Binary
    Download the appropriate binary for your platform from the assets below.

    #### Docker
    ```bash
    docker pull ghcr.io/qj0r9j0vc2/alert-bridge:{{ .Tag }}
    ```

    #### Verify Checksum
    ```bash
    sha256sum -c checksums.txt
    ```
  footer: |
    ---
    **Full Changelog**: https://github.com/qj0r9j0vc2/alert-bridge/compare/{{ .PreviousTag }}...{{ .Tag }}
